### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by arkmand2015** [TobiasLee/SeqGAN_Poem#1]
Hello @TobiasLee , 
1 . how can I run this model?
2. How can I run it with my own text data
Thank you!

**Comment by TobiasLee** [comment]
Hi @arkmand2015 ,
1. Run `seqgan.py` to train the model and see the result.
2. You can pre-prcoess you own data to index token and put them in `train.txt`, which contains true data that generator can learn from.
The code is totally a mess since I just wanna quickly implemented my project, I will rewrite the code and provide a detailed README when I have time~

**Comment by Arkamnd** [comment]
Thank you very much @TobiasLee .

**Comment by Arkamnd** [comment]
Hi @TobiasLee,
 are you doing the generation at the character-level or word-level?

**Comment by TobiasLee** [comment]
@Arkamnd You're welcome. Character-level, which is most common practice.

**Comment by Arkamnd** [comment]
Hi @TobiasLee, thank you for your answers. 

1. In your train.txt file, each line represents a poem?
2. Each Id (number) is a word?

**Comment by TobiasLee** [comment]
@arkmand2015  Yes and yes.
